### ISSUE TITLE
HRTimer: Minimum compare value does not apply under some conditions

### ISSUE THREAD

**Issue by liampwll** [JCGobbi/Nucleo-STM32G474RE#3]
In STM32.HRTimers.Set_Compare_Value the compare value is set to the minimum allowed value under normal conditions. However, under some conditions the compare value may be set to zero, as noted on page 850 of RM0440 Rev 8. I'm not sure whether you want to adjust the check there, move it to a precondition, or get rid of it all together.

https://github.com/JCGobbi/Nucleo-STM32G474RE/blob/391658fe04dc9aae182267edffd899b291225df6/ADL/drivers/stm32-hrtimers.adb#L1250-L1255

**Comment by JCGobbi** [comment]
I have removed the check in the Set_Compare_Value and added comments in the stm32-hrtimers.ads file for these procedures. The programmer may build its own checking routine.
