### ISSUE TITLE
The ADC on this MCU requires some extra steps to enable

### ISSUE THREAD

**Issue by liampwll** [JCGobbi/Nucleo-STM32G474RE#5]
As noted in section 21.4.6 of RM0440, the ADC on this MCU requires some extra steps to enable it that aren't required on other STM32s:

> By default, the ADC is in Deep-power-down mode where its supply is internally switched off to reduce the leakage currents (the reset state of bit DEEPPWD is 1 in the ADC_CR register).
To start ADC operations, follow the sequence below:
> 1. Exit Deep-power-down mode by clearing DEEPPWD bit.
> 2. Enable the ADC voltage regulator by setting ADVREGEN.
> 3. Wait for the startup time to configure the ADC (refer to the device datasheet for the value of the startup time). 

Calibration as described in 21.4.8 may also be required, I was not able to find details on the performance of the ADC before calibration.

**Comment by JCGobbi** [comment]
I have changed the Enable procedure to follow the manual and added a calibration procedure.
I have added new routines for setting input type: single-ended or differential. For this I had to modify the STM32G474xx.svd file and stm32_svd-adc.ads.
