### ISSUE TITLE
Setting ADDIS does not immediately disable the ADC, causing the post-condition to sometimes fail.

### ISSUE THREAD

**Issue by liampwll** [JCGobbi/Nucleo-STM32G474RE#6]
Currently STM32.ADC.Disable sets ADDIS to False and then immediately returns, which causes the post-condition to fail if the ADC is not disabled fast enough. The reference manual is not clear on how long it could take for the ADC to become disabled, so I do not know if it is better to add a busy-loop here or remove the post-condition. I think that it will wait for all queued conversions to be completed, but the manual does not say this.

Relevant lines:
https://github.com/JCGobbi/Nucleo-STM32G474RE/blob/06a071b9e380f5412d1eebaf255d5129ed454e69/ADL/drivers/stm32-adc.adb#L103
https://github.com/JCGobbi/Nucleo-STM32G474RE/blob/06a071b9e380f5412d1eebaf255d5129ed454e69/ADL/drivers/stm32-adc.ads#L114

Relevant excerpt from the manual:
> Bit 1 ADDIS: ADC disable command
> This bit is set by software to disable the ADC (ADDIS command) and put it into power-down state (OFF state).
> It is cleared by hardware once the ADC is effectively disabled (ADEN is also cleared by hardware at this time).
> 0: no ADDIS command ongoing
> 1: Write 1 to disable the ADC. Read 1 means that an ADDIS command is in progress.
> Note: The software is allowed to set ADDIS only when ADEN = 1 and both ADSTART = 0 and JADSTART = 0 (which ensures that no conversion is ongoing).

**Comment by JCGobbi** [comment]
The manual indicates that ADDIS is cleared by hardware once the ADC is effectively disabled (ADEN is also cleared by hardware at 
this time). So it was added a loop waiting ADDIS = 0 and ADEN = 0 to guarantee the disabled state before the end of routine to validate the post-condition every time.
