### ISSUE TITLE
Timers 15, 16, and 17 require setting BDTR.MOE to enable output but this is blocked by a precondition

### ISSUE THREAD

**Issue by liampwll** [JCGobbi/Nucleo-STM32G474RE#7]
As stated by the title, these timers require Enable_Main_Output to be called but the precondition on that procedure does not allow for that. I have not checked exactly what the Advanced_Timer precondition function covers so I do not know if these timers can just be included in the precondition: https://github.com/JCGobbi/Nucleo-STM32G474RE/blob/6f85124dd2fe8e02ce92c5d3121bb7c1242e9e64/ADL/drivers/stm32-timers.ads#L794

**Comment by JCGobbi** [comment]
These timers have the advanced functions of complementary outputs and dead-time insertion, so they were added to that precondition.
